name: Core
version: '${project.version}'
main: com.skips.core.main.Main
api-version: 1.18
authors: [ Skips, Sebastian ]
description: Core plugin for the server.
depend: [WorldEdit]
commands:
  arena:
