name: Core
version: 1.0
main: com.skips.core.main.Main
api-version: 1.18
authors: [ Skips, Sebastian ]
description: Core plugin for the server.
#depend: [WorldEdit]
commands:
  arena:
    description: Allows you to set a new kit pvp arena.
  setspawn:
    description: Allows you to set a spawn point for the server.
  spawn:
    description: Allows you to teleport to the set spawn point for the server.
